# Generated by Django 5.2.4 on 2025-07-24 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadPost',
            fields=[
                ('postid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=2000)),
                ('upvotes', models.JSONField(blank=True, default=list)),
                ('downvotes', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('commenttext', models.CharField(max_length=2000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='thread.threadpost')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='thread.user')),
            ],
        ),
    ]
